CREATE DATABASE maximal;
-- DROP DATABASE maximal;

USE maximal;

CREATE TABLE usuario(
	idUsuario INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(12) NOT NULL,
    fkLocalizacao INT NOT NULL,
    FOREIGN KEY fkLocalizacao (fkLocalizacao)
    REFERENCES localizacao (idLocalizacao)
);

CREATE TABLE hospital (
	idHospital INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	endereco VARCHAR(200) NOT NULL,
	fkLocalizacao INT,
    FOREIGN KEY fkLocalizacao (fkLocalizacao)
    REFERENCES localizacao (idLocalizacao)
);

SHOW TABLES; 

DROP TABLE hospital;
DROP TABLE localizacao;
DROP TABLE classificacao;
DROP TABLE comentario;
DROP TABLE usuario;
DROP TABLE servicoHospitalar;
DROP TABLE servico;

CREATE TABLE localizacao (
	idLocalizacao INT PRIMARY KEY AUTO_INCREMENT,
	cidade VARCHAR(45),
	estado VARCHAR(45) NOT NULL,
  regiao VARCHAR(45) NOT NULL
);

CREATE TABLE classificacao (
  idClassificacao INT PRIMARY KEY AUTO_INCREMENT,
  tipo VARCHAR(10) NOT NULL,
  CONSTRAINT chk_tipo 
	CHECK (tipo IN ('ajuda', 'adocao', 'doacao', 'aleatorio'))
);

CREATE TABLE servico (
	idServico INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100)
);

CREATE TABLE servicoHospitalar (
	fkHospital INT,
	fkServico INT,
    PRIMARY KEY (fkHospital, fkServico),
    FOREIGN KEY (fkHospital) REFERENCES hospital(idHospital),
    FOREIGN KEY (fkServico) REFERENCES servico(idServico)
);

INSERT INTO localizacao (cidade, estado, regiao) VALUES
	('Macapá', 'Amapá', 'Norte'),
    ('Belém', 'Pará', 'Norte'),
    ('Manaus', 'Amazonas', 'Norte'),
    ('Boa Vista', 'Roraima', 'Norte'),
    ('Palmas', 'Tocantins', 'Norte'),
    ('São Luís', 'Maranhão', 'Nordeste'),
    ('Teresina', 'Piauí', 'Nordeste'),
    ('Fortaleza', 'Ceará', 'Nordeste'),
    ('Fortaleza', 'Ceará', 'Nordeste'),
	('Areia', 'Paraíba', 'Nordeste'),
	('Recife', 'Pernambuco', 'Nordeste'),
	('Jaboatão dos Guararapes', 'Pernambuco', 'Nordeste'),
    ('Caruaru', 'Pernambuco', 'Nordeste'),
    ('Aracaju', 'Sergipe', 'Nordeste'),
    ('Salvador', 'Bahia', 'Nordeste'),
	('Ilhéus', 'Bahia', 'Nordeste'),
	('Goiânia', 'Goiás', 'Centro-Oeste'),
    ('Taguatinga', 'Distrito Federal', 'Centro-Oeste'),
	('Brasília', 'Distrito Federal', 'Centro-Oeste'),
    ('Cuiabá', 'Mato Grosso', 'Centro-Oeste'),
	('Campo Grande', 'Mato Grosso do Sul', 'Centro-Oeste'),
	('Alegre', 'Espírito Santo', 'Sudeste'),
    ('Vila Velha', 'Espírito Santo', 'Sudeste'),
	('Belo Horizonte', 'Minas Gerais', 'Sudeste'),
    ('Niterói', 'Rio de Janeiro', 'Sudeste'),
	('Seropédica', 'Rio de Janeiro', 'Sudeste'),
	('Rio de Janeiro', 'Rio de Janeiro', 'Sudeste'),
	('São Paulo', 'São Paulo', 'Sudeste'),
    ('Osasco', 'São Paulo', 'Sudeste'),
	('Ferraz de Vasconcelos', 'São Paulo', 'Sudeste'),
	('Taubaté', 'São Paulo', 'Sudeste'),
	('São Bernardo do Campo', 'São Paulo', 'Sudeste'),
	('Curitiba', 'Paraná', 'Sul'),
    ('Londrina', 'Paraná', 'Sul'),
	('Umuarama', 'Paraná', 'Sul'),
	('Florianópolis', 'Santa Catarina', 'Sul'),
	('Curitibanos', 'Santa Catarina', 'Sul'),
	('Canoas', 'Rio Grande do Sul', 'Sul'),
    ('Porto Alegre', 'Rio Grande do Sul', 'Sul'),
	('Santa Maria', 'Rio Grande do Sul', 'Sul');
    
INSERT INTO localizacao (cidade, estado, regiao) VALUES
  (NULL, 'Acre', 'Norte'),
  (NULL, 'Alagoas', 'Nordeste'),
  (NULL, 'Amapá', 'Norte'),
  (NULL, 'Amazonas', 'Norte'),
  (NULL, 'Bahia', 'Nordeste'),
  (NULL, 'Ceará', 'Nordeste'),
  (NULL, 'Distrito Federal', 'Centro-Oeste'),
  (NULL, 'Espírito Santo', 'Sudeste'),
  (NULL, 'Goiás', 'Centro-Oeste'),
  (NULL, 'Maranhão', 'Nordeste'),
  (NULL, 'Mato Grosso', 'Centro-Oeste'),
  (NULL, 'Mato Grosso do Sul', 'Centro-Oeste'),
  (NULL, 'Minas Gerais', 'Sudeste'),
  (NULL, 'Pará', 'Norte'),
  (NULL, 'Paraíba', 'Nordeste'),
  (NULL, 'Paraná', 'Sul'),
  (NULL, 'Pernambuco', 'Nordeste'),
  (NULL, 'Piauí', 'Nordeste'),
  (NULL, 'Rio de Janeiro', 'Sudeste'),
  (NULL, 'Rio Grande do Norte', 'Nordeste'),
  (NULL, 'Rio Grande do Sul', 'Sul'),
  (NULL, 'Rondônia', 'Norte'),
  (NULL, 'Roraima', 'Norte'),
  (NULL, 'Santa Catarina', 'Sul'),
  (NULL, 'São Paulo', 'Sudeste'),
  (NULL, 'Sergipe', 'Nordeste'),
  (NULL, 'Tocantins', 'Norte');
  
  SELECT * FROM localizacao;
    
INSERT INTO hospital (nome, endereco, fkLocalizacao) VALUES 
	('Hospital Veterinário Público de Macapá','Ramal do Alemão – Fazendinha', 1),
    ('Hospital Veterinário Municipal Dr. Vahia', 'Rod. do Tapanã, 281 – Tapanã (Icoaraci)', 2),
    ('Hospital Veterinário Mário Dias Teixeira', 'Via Felisberto Camargo – Universitário', 2),
    ('Hospital de Medicina Veterinária Universidade Nilton Lins', 'Av. Prof. Nilton Lins, 3259, Parque das Laranjeiras', 3),
    ('Complexo Veterinário do Centro de Ciências Agrárias da UFRR', 'Av. Via 2, Boa Vista – Roraima – Campus Cauamé', 4),
    ('Hospital Veterinário do CEULP/ULBRA', 'Q. 1501 Sul, Av. Joaquim Teotônio Segurado, s/n – Plano Diretor Sul', 5),
    ('Hospital Veterinário Universitário da UEMA', 'São Cristóvão', 6),
    ('Hospital Veterinário Universitário (HVU)', 'UFPI Campus Universitário Ministro Petrônio Portella, Bairro Ininga', 7),
	('Clínica Veterinária de Fortaleza – Jacó', 'Av. da Saudade, esquina com a Av. dos Paroaras – Passaré.', 8),
    ('Hospital Veterinário Professor Sylvio Barbosa Cardoso da FAVET/UECE', 'R. Betel, SN – Itaperi,', 9),
	('Hospital Veterinário da Universidade Federal da Paraíba (UFPB)','Campus II – CCA – UFPB – Cidade Universitária', 10),
	('Hospital Veterinário da Universidade Federal Rural de Pernambuco (UFRPE)', 'R. Manuel de Medeiros, sem número, Dois Irmãos', 11),
	('Hospital Veterinário do Recife Robson José Gomes de Melo (HVR)','Av. Prof. Estevão Francisco da Costa, s/n – Cordeiro', 11),
	('Unidade Básica de Saúde (UBS) Pet de Jaboatão dos Guararapes', 'Praça Murilo Braga, no bairro de Cavaleiro, Jaboatão dos Guararapes', 12),
    ('AME Animal Caruaru', 'Rua Rádio Cultura, 1000, Indianópolis', 13),
    ('Hospital Veterinário Dr. Vicente Borelli da Faculdade Pio Décimo', 'Rua Estância, 382 – Centro', 14),
    ('Hospital Veterinário HOSPMEV (UFBA)', 'Av. Ademar de Barros, nº 500, Ondina', 15),
	('Hospital Veterinário da UESC', 'Rodovia Jorge Amado, Km 16, Salobrinho Campus Soane Nazaré de Andrade', 16),
	('Hospital Veterinário da UFG', 'Rodovia Goiânia – Nova Veneza, Km 8 Campus Samambaia', 17),
    ('Hospital Veterinário Público (HVEP)', 'Parque Lago do Cortado – Taguatinga Norte', 18 ),
	('Hospital Veterinário da UNB (Universidade de Brasília)', 'L4 Norte – Asa Norte', 19),
    ('Hospital Veterinário da UFMT (Universidade Federal do Mato Grosso)', 'Av. Fernando Corrêa da Costa, nº 2367 – Bairro Boa Esperança', 20),
	('Hospital Veterinário da Universidade Federal de Mato Grosso do Sul (UFMS)', 'Av. Senador Felinto Muller, 2443', 21),
	('Hospital Veterinário Dom Bosco', 'Avenida Tamandaré, 6.000', 21),
	('Hospital veterinário da Universidade do Espírito Santo (UFES)', 'BR 482, Km 63, Área Experimental de Rive', 22),
    ('Hospital Veterinário da Universidade Vila Velha (UVV)', 'Rua Viana, s/nº – Boa Vista', 23),
	('Hospital Público Veterinário Belo Horizonte', 'Rua Pedro Bizzoto, 230, bairro Madre Gertrudes', 24),
	('Hospital veterinário da UFMG', 'Av. Presidente Carlos Luz, 5162 – Pampulha', 24),
    ('Hospital de Medicina Veterinária Professor Firmino Marsico Filho (Huvet)', 'Av. Ary Parreiras, 503, Vital Brazil', 25),
	('Hospital Veterinário da UFRRJ', 'Rod. BR 465, km 7, CEP 23890-000', 26),
	('Sociedade União Internacional Protetora dos Animais (Suipa)', 'Av. Dom Hélder Câmara, nº 1.801 – Benfica', 27),
	('Hospital Veterinário da Zona Leste – São Paulo', 'Av Salim Farah Maluf, esquina com a Rua Ulisses Cruz, Lado Par Tatuapé', 28),
	('Hospital Veterinário da Zona Sul – São Paulo', 'Rua Agostino Togneri, 153 – Jurubatuba', 28),
	('Hospital Veterinário da Zona Norte – São Paulo', 'Rua Atílio Piffer, 687 – Casa Verde', 28),
	('Hospital Veterinário da Zona Oeste – São Paulo', 'Av. Professor Orlando Marques de Paiva, 87 – Butantã (USP)', 28),
    ('Parque Industrial Mazzei', 'Av. Franz Voegeli, 930 – Jardim Wilson', 29),
	('Pet Parque Osasco', 'Av. Franz Voegeli, 930 – Jardim Wilson', 29),
	('Hospital Veterinário Ferraz de Vasconcelos', 'Rua das Américas, 35, Sítio Paredão', 30),
	('Hospital Veterinário Taubaté', 'Av. Juscelino Kubitschek de Oliveira, 214 – Jardim Eulalia', 31),
	('Hospital Veterinário da Universidade da Anhanguera', 'Avenida Dr. Rudge Ramos, nº 1.701', 32),
	('Hospital Veterinário da Universidade Federal do Paraná (UFPR)', 'Rua dos Funcionários, nº1540, Juvevê', 33),
	('Hospital Veterinário da PUC-PR', 'Rua Rockefeller 1311 – Rebouças', 33),
    ('Clínica Escola de Medicina Veterinária da Tuiuti', 'Rua Sidney Antonio Rangel Santos, 245 -Santo Inácio', 33),
	('Hospital Veterinário da Universidade Estadual de Londrina (UEL)', 'Rodovia Celso Garcia Cid/Pr 445 Km 380, Campus Universitário', 34),
	('Hospital Veterinário da Universidade Paranaense (UNIPAR)', 'Rod, PR, 480 – km-14 S/N – Parque Bandeirantes', 35),
	('Diretoria do Bem-Estar Animal (DIBEA)', 'Rodovia SC-401, nº 114 – DIBEA – Itacorubi', 36),
	('Clínica Veterinária Escola – CVE – UFSC Curitibanos', 'Avenida Advogado Sebastião Calomeno, 400. CEDUP – São Francisco', 37),
	('Hospital Veterinário da Universidade Luterana do Brasil (ULBRA)', 'Av. Farroupilha, 8001 – Bairro São José', 38),
    ('Hospital Veterinário da UFRGS', 'Av. Bento Gonçalves, nº 9090, Agronomia', 39),
	('Hospital Veterinário da UFSM', 'Avenida Roraima, 1000, Prédio 97, Cidade Universitária', 40);
    
INSERT INTO servico (nome) VALUES
	('Consultas agendadas'),
	('Exames de raio-X e ultrassom'),
	('Ambulatório'),
	('Cirurgia de pequena e média complexidade'),
	('Atendimento de emergência e urgência'),
	('Nutrição para animais em observação'),
	('Vacinação antirrábica'),
    ('Exames laboratoriais'),
	('Castração'),
    ('Clínica geral'),
	('Dermatologia'),
	('Oftalmologia'),
	('Cardiologia'),
	('Nefrologia'),
	('Reprodução'),
	('Infectologia'),
	('Endoscopia'),
	('Eletrocardiograma'),
	('Ecocardiograma'),
    ('Atendimento a animais domésticos e silvestres'),
	('Tomografia'),
	('Laboratório de diagnóstico'),
    ('Exames de necropsia'),
	('Atendimento clínico e cirúrgico conjunto'),
    ('Clínica médica de pequenos animais'),
	('Clínica cirúrgica de pequenos animais'),
	('Anestesiologia'),
	('Internação'),
	('Ortopedia'),
	('Oncologia'),
	('Odontologia'),
	('Clínica médica de animais de produção e equinos'),
	('Clínica cirúrgica de animais de produção e equinos'),
    ('Atendimento clínico e cirúrgico de pequenos, médios e grandes animais'),
    ('Clínica e cirurgia de grandes animais'),
	('Patologia clínica veterinária'),
	('Tratamento de doenças parasitárias'),
    ('Consultas clínicas'),
	('Endocrinologia'),
	('Neurologia'),
	('Urgências e emergências'),
	('Aplicação de medicamentos'),
	('Cirurgias gerais (tecidos moles e ortopédicas)'),
	('Soroterapia'),
    ('Unidade de tratamento intensivo (UTI)'),
    ('Orientação técnica nas práticas de criação'),
    ('Identificação e controle de natalidade de animais abandonados'),
    ('Radiologia'),
    ('Ultrassonografia'),
    ('Histopatologia'),
    ('Necropsia'),
    ('Atendimento ambulatorial'),
    ('Campanhas de adoção'),
    ('Resgate de animais feridos, doentes ou vulneráveis'),
    ('Canil rotativo'),
    ('Cirurgias oncológicas'),
    ('Quimioterapia'),
    ('Diagnóstico clínico'),
    ('Avaliação clínica'),
    ('Estabilização do quadro clínico'),
    ('Procedimentos clínicos gerais'),
    ('Curativos simples e complexos'),
    ('Aplicação de medicações diversas'),
    ('Imobilização'),
    ('Teste de compatibilidade'),
    ('Testes rápidos (cinomose, parvovirose, erliquiose, giardia, dirofilaria, FIV, FELV)'),
    ('Ultrassonografia abdominal total'),
    ('Cistocentese guiada por ultrassom cervical'),
    ('Biópsia guiada por ultrassom'),
    ('Citologia guiada'),
    ('Ultrassonografia craniana, tireoide e ocular'),
    ('Raios-X'),
    ('Urografia excretora'),
    ('Contraste gastrointestinal'),
	('Transfusões'),
    ('Punções'),
    ('Oxigenioterapia'),
    ('Exame de líquido cefaloraquidiano'),
    ('Testes laboratoriais'),
    ('Análises clínicas (hemograma, bioquímica)'),
    ('Obstetrícia'),
    ('Clínica médica e cirúrgica para pequenos animais'),
    ('Clínica médica e cirúrgica para grandes animais'),
    ('Fluidoterapia'),
	('Atos anestésicos e cirúrgicos'),
	('Exames parasitológicos'),
	('Exames microbiológicos'),
	('Exames complementares de imagem'),
    ('Toxicologia'),
	('Vacina Leishmaniose'),
	('Vacina Raiva'),
	('Vacina Sêxtupla'),
	('Vacina Tríplice Felina'),
	('Reabilitação'),
	('Eutanásia'),
	('Exames Leishmaniose'),
	('Histopatologia/Necropsia'),
    ('Acupuntura'),
	('Clínica médica de cães'),
	('Clínica médica de gatos'),
	('Consultas ortopédicas'),
	('Esterilização'),
    ('Exames de imagem'),
	('Medicina integrativa'),
	('Patologias'),
    ('Videocirurgia'),
	('Exames de rotina'),
	('Medicamentos'),
	('Laboratório de análises clínicas'),
	('Laboratório de diagnóstico por imagem'),
	('Laboratório de microbiologia e doenças infecciosas'),
	('Laboratório de parasitologia veterinária'),
	('Laboratório de patologia animal'),
	('Laboratório de reprodução animal'),
	('Alergologia veterinária'),
	('Clínica médica e cirúrgica de animais de produção'),
	('Clínica médica e cirúrgica de animais selvagens'),
	('Dermatologia veterinária'),
	('Endocrinologia veterinária'),
	('Odontologia veterinária de pequenos animais'),
	('Fisioterapia'),
    ('Não informado');

INSERT INTO servicoHospitalar (fkHospital, fkServico) VALUES
	(1, 1),
	(1, 2),
	(1, 3),
	(1, 4),
	(1, 5),
	(1, 6),
	(1, 7),
    (2, 1),
	(2, 2),
	(2, 4),
	(2, 5),
	(2, 8),
	(2, 9),
    (3, 2),
	(3, 4),
	(3, 10),
	(3, 11),
	(3, 12),
	(3, 13),
	(3, 14),
	(3, 15),
	(3, 16),
	(3, 17),
	(3, 18),
	(3, 19),
    (4, 2),
	(4, 4),
	(4, 20),
	(4, 21),
	(4, 22),
    (5, 2),
	(5, 8),
	(5, 9),
	(5, 23),
	(5, 24),
    (6, 2),
	(6, 8),
	(6, 11),
	(6, 15),
	(6, 25),
	(6, 26),
	(6, 27),
	(6, 28),
	(6, 29),
	(6, 30),
	(6, 31),
	(6, 32),
	(6, 33),
    (7, 34),
    (8, 25),
	(8, 26),
	(8, 27),
	(8, 2),
	(8, 8),
	(8, 35),
	(8, 36),
	(8, 37),
    (9, 2),
	(9, 8),
	(9, 9),
	(9, 11),
	(9, 13),
	(9, 29),
	(9, 30),
	(9, 38),
	(9, 39),
	(9, 40),
	(9, 41),
	(9, 42),
	(9, 43),
	(9, 44),
    (10, 1),
    (10, 7),
    (10, 2),
    (10, 27),
    (10, 4),
    (10, 45),
    (10, 46),
    (10, 47),
    (11, 5),
    (11, 4),
    (11, 48),
    (11, 49),
    (11, 50),
    (11, 12),
    (11, 51),
    (12, 1),
    (12, 11),
    (12, 30),
    (12, 12),
    (12, 2),
    (13, 1),
    (13, 8),
    (13, 4),
    (14, 1),
    (14, 7),
    (14, 9),
    (14, 8),
    (15, 52),
    (15, 53),
    (15, 7),
    (15, 54),
    (15, 9),
    (15, 55),
    (16, 56),
    (16, 57),
    (16, 1),
    (16, 58),
    (16, 5),
    (16, 59),
    (16, 60),
    (16, 61),
    (16, 62),
    (16, 63),
    (16, 7),
    (16, 64),
    (16, 65),
    (16, 66),
    (16, 67),
    (16, 68),
    (16, 69),
    (16, 70),
    (16, 71),
    (16, 2),
    (16, 72),
    (16, 73),
    (16, 74),
    (17, 10),
	(17, 24),
	(17, 25),
	(17, 26),
	(17, 28),
	(17, 29),
	(17, 30),
	(17, 31),
	(17, 32),
	(17, 33),
	(17, 21),
	(17, 22),
	(17, 35),
    (18, 10),
	(18, 4),
	(18, 26),
	(18, 21),
	(18, 22),
	(19, 26),
	(19, 4),
	(19, 24),
	(19, 27),
	(19, 48),
	(19, 21),
	(19, 34),
    (20, 1),
	(20, 8),
    (20, 3),
    (20, 4),
    (20, 42),
    (21, 10),
	(21, 4),
    (21, 12),
    (21, 9),
    (21, 8),
    (20, 7),
	(20, 59),
	(20, 75),
	(20, 76),
	(20, 74),
	(20, 77),
	(20, 18),
	(20, 78),
	(20, 79),
	(20, 80),
	(21, 81),
	(21, 82),
	(21, 83),
	(21, 27),
	(21, 2),
	(22, 4),
	(22, 10),
	(22, 60),
	(22, 2),
	(22, 15),
	(22, 36),
	(23, 34),
	(23, 8),
	(23, 84),
	(23, 85),
	(23, 86),
	(23, 87),
    (24, 20),
	(24, 9),
	(24, 4), 
	(24, 1), 
	(24, 5), 
	(24, 8), 
	(24, 28),
	(24, 31),
	(24, 30),
	(24, 7), 
	(25, 25),
	(25, 32),
	(25, 26),
	(25, 27),
	(25, 48),
	(25, 36),
	(26, 13),
	(26, 32),
	(26, 31),
	(26, 29),
	(26, 11),
	(26, 12),
	(26, 30),
	(26, 19),
	(26, 96),
	(26, 97),
	(26, 98),
	(26, 36),
	(26, 49),
	(26, 95),
	(26, 15),
	(26, 44),
	(26, 91),
	(26, 50),
	(26, 92),
	(26, 93),
	(26, 94),
	(26, 90),
    (27, 34),
	(27, 27),
	(27, 98),
	(27, 48),
	(27, 9),
	(28, 99),
	(28, 100),
	(28, 13),
	(28, 11),
	(28, 12),
	(28, 30),
	(28, 14),
	(28, 40),
	(28, 101),
	(28, 20),
	(28, 4),
	(28, 27),
	(28, 48),
	(29, 1),
	(29, 102),
	(29, 13),
	(29, 48),
	(29, 103),
	(30, 10),
	(30, 12),
	(30, 4),
	(30, 29),
	(30, 27),
	(30, 48),
	(30, 50),
	(30, 13),
	(30, 31),
	(30, 40),
	(30, 30),
	(30, 39),
	(30, 16),
	(31, 10),
	(31, 12),
	(31, 4),
	(31, 29),
	(31, 27),
	(31, 48),
	(31, 50),
	(31, 13),
	(31, 31),
	(31, 40),
	(31, 30),
	(31, 39),
	(31, 16),
	(32, 10),
	(32, 12),
	(32, 4),
	(32, 29),
	(32, 27),
	(32, 48),
	(32, 50),
	(32, 13),
	(32, 31),
	(32, 40),
	(32, 30),
	(32, 39),
	(32, 16),
	(33, 10),
	(33, 12),
	(33, 4),
	(33, 29),
	(33, 27),
	(33, 48),
	(33, 50),
	(33, 13),
	(33, 31),
	(33, 40),
	(33, 30),
	(33, 39),
	(33, 16),
    (34, 29),
	(34, 12),
	(34, 13),
	(34, 39),
	(34, 27),
	(35, 10),
	(35, 4),
	(35, 29),
	(36, 1),
	(37, 10),
	(37, 4),
	(37, 29),
	(37, 39),
	(37, 11),
	(38, 25),
	(38, 32),
	(38, 26),
	(38, 27),
	(38, 48),
	(38, 36),
	(39, 104),
	(39, 8),
	(39, 31),
	(39, 12),
	(39, 30),
	(39, 4),
	(39, 7),
	(40, 27),
	(40, 4),
	(40, 10),
	(40, 48),
	(40, 22),
	(40, 105),
	(40, 106),
    (41, 101),
	(41, 27),
	(41, 4),
	(41, 29),
	(41, 11),
	(41, 8),
	(41, 28),
	(41, 31),
	(41, 12),
	(41, 30),
	(41, 40),
	(41, 49),
	(41, 50),
	(41, 107),
	(42, 108),
	(42, 1),
	(42, 109),
	(42, 28),
	(43, 110),
	(43, 111),
	(43, 112),
	(43, 113),
	(43, 114),
	(43, 115),
	(43, 116),
	(43, 27),
	(43, 117),
	(43, 25),
	(43, 118),
	(43, 119),
	(43, 120),
	(43, 121),
	(43, 15),
	(44, 122),
	(45, 34),
	(45, 87),
	(46, 34),
	(46, 28),
	(46, 31),
	(46, 30),
	(46, 121),
	(46, 101),
	(46, 8),
	(46, 22),
	(46, 37),
	(46, 36),
	(46, 48),
    (47, 10),
	(47, 11),
	(47, 122),
	(47, 12),
	(47, 39),
	(47, 30),
	(47, 40),
	(47, 29),
	(47, 4),
	(48, 1),
	(48, 49),
	(48, 50),
	(48, 40);

SELECT * FROM usuario;